### ISSUE TITLE
time sync for prepareForSleep and prepareForDaytime will constantly fire for 15minutes

### ISSUE THREAD

**Issue by andysheen** [interactionresearchstudio/RFIDBirdFeeder#7]
Need to add rtcdata variable to track if time has been synced or not to stop the functioned continuously firing

**Comment by mikevanis** [comment]
Theoretically, it should only fire once because it will sync time with the server and jump ahead by a few minutes, effectively debouncing it. I remember testing this before, but sounds like we need to look into it.
